[project]
name = "logger-singleton-prototype"
version = "0.1.0"
description = "logger prototype"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.13.0",
]

[dependency-groups]
dev = [
    "ruff>=0.7.2",
]
